name: 'KRCUAT 10-50'

on:
  push:
    branches: [ "master" ]
  pull_request:
    paths:
      - 'env/base/**'
      - 'env/koreacentral/uat/**'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.11.4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: |
        cd ./env/base/10-network/
        terraform init -backend-config="key=10-network.tfstate" -backend-config="resource_group_name=rg-econ-prod-state" -backend-config="storage_account_name=srsteconprodstate" -backend-config="container_name=stceconprodstate"

    - name: Terraform Plan
      run: |
        cd ./env/base/10-network/
        terraform plan -var-file="../../koreacentral/uat/10-network/10-network.auto.tfvars" -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        cd ./env/base/10-network/
        terraform apply -auto-approve tfplan
